import csv

# Mapping of specific job titles to general categories
job_title_to_category = {
    "Event Planner": "Event Planning",
    "Miami Heat Dancer": "Entertainment",
    "Financial Management Consultant": "Finance",
    "Nanny": "Childcare",
    "Graduate Student": "Education",
    "Attorney": "Law",
    "Actress": "Entertainment",
    "Commercial Real Estate Agent": "Real Estate",
    "Special Ed. Teacher": "Education",
    "Production Coordinator": "Management",
    "Hooters Waitress": "Hospitality",
    "Power Tool Sales Rep.": "Sales",
    "Photographer": "Arts",
    "Business Development Director": "Management",
    "Neuropsychologist": "Healthcare",
    "Doctor": "Healthcare",
    "Bar Manager": "Hospitality",
    "Retail Manager": "Retail",
    "Advertising Executive": "Marketing",
    "Insurance Representative": "Insurance",
    "6th Grade Teacher": "Education",
    "Technology Specialist": "Technology",
    "School Psychologist": "Education",
    "College Student": "Education",
    "Executive Recruiter": "Human Resources",
    "Registered Nurse": "Healthcare",
    "Flight Attendant": "Hospitality",
    "Assistant Financial Advisor": "Finance",
    "Marriage Therapy Trainee": "Counseling",
    "Airline Supervisor": "Hospitality",
    "Graphic Artist": "Arts",
    "Radio Sales": "Sales",
    "Publications Quality Control": "Quality Control",
    "Strategic Planning Analyst": "Management",
    "Psychologist": "Healthcare",
    "3rd Grade Teacher": "Education",
    "Radiological Technologist": "Healthcare",
    "Interior Designer": "Design",
    "Paralegal": "Legal",
    "Former NBA Cheerleader": "Entertainment",
    "1st Grade Teacher": "Education",
    "Communications Specialist": "Communication",
    "Student": "Education",
    "General Contractor": "Construction",
    "Architect Designer": "Architecture",
    "Model": "Entertainment",
    "Pharmaceutical Salesperson": "Sales",
    "Prosthetic Technician": "Healthcare",
    "Swim Instructor": "Sports",
    "Professional Cheerleader": "Entertainment",
    "LASIK Eye & Skin Center Manager": "Healthcare",
    "Consultant": "Consulting",
    "Executive Assistant": "Administration",
    "Massage Therapist": "Healthcare",
    "Hairstylist": "Beauty",
    "Professional Soccer Player": "Sports",
    "Account Manager": "Management",
    "Bank Representative": "Finance",
    "Singer": "Entertainment",
    "Fashion PR Manager": "Fashion",
    "Teacher": "Education",
    "Publicist": "Public Relations",
    "Marketing manager": "Marketing",
    "Realtor": "Real Estate",

    "Ultrasound technician": "Healthcare",
    "Event planner": "Event Planning",
    "Interior designer": "Design",
    "Journalist": "Media",
    "Hotel concierge": "Hospitality",
    "Beer chemist": "Science",
    "Restaurateur": "Hospitality",
    "Dancer": "Entertainment",
    "Physician": "Healthcare",
    "Registered nurse": "Healthcare",
    "Assistant buyer": "Retail",
    "Dolphin trainer": "Animal Care",
    "Broadcast marketer": "Marketing",
    "Policy advisor": "Government",
    "Make-up artist": "Beauty",
    "Social Worker": "Social Services",
    "Assistant": "Administration",
    "Graphic Designer": "Design",
    "Project Manager": "Management",
    "Medical student": "Medical",
    "Boutique owner": "Retail",
    "Sales Manager": "Sales",
    "Organ donor coordinator": "Healthcare",
    "Financial analyst": "Finance",
    "Sorority recruiter": "Recruitment",
    "Boutique manager": "Retail",
    "Medical equipment sales rep": "Sales",
    "Radio sales": "Sales",
    "Waitress": "Hospitality",
    "Former Miss Illinois": "Beauty",
    "Executive coordinator": "Administration",
    "Health care manager": "Healthcare",
    "Hedge fund analyst": "Finance",
    "Real estate sales/development": "Real Estate",
    "Phoenix Suns Cheerleader": "Athlete",
    "Internet marketing executive": "Marketing",
    "Acupuncturist": "Healthcare",
    "Account manager": "Management",
    "Executive assistant": "Administration",
    "Boutique sales worker": "Retail",
    "Bar manager": "Hospitality",
    "Esthetician": "Beauty",
    "Publishing sales executive": "Sales",
    "News anchor": "Media",
    "Law student": "Law",
    "Biology teacher": "Education",

    "Graduate student": "Education",
    "Account representative": "Sales",
    "Emergency room nurse": "Healthcare",
    "Project analyst": "Business",
    "Pharmaceutical sales rep.": "Sales",
    "Account Executive": "Management",
    "Fashion designer": "Fashion",
    "Advertising coordinator": "Marketing",
    "Singer-songwriter": "Music",
    "Medical sales representative": "Sales",
    "Children's book author": "Writing",
    "Vendor": "Sales",
    "Personal trainer": "Fitness",
    "Church marketing rep.": "Marketing",
    "Administrative assistant": "Administration",
    "Biology student": "Education",
    "Attorney and former White House aide": "Law",
    "Youth minister": "Religion",
    "Cocktail waitress": "Hospitality",
    "Real estate marketing rep.": "Real Estate",
    "Sales Representative": "Sales",
    "Department Store Buyer": "Retail",
    "Medical Marketing Representative": "Marketing",
    "Lacrosse Coach": "Sports",
    "Dental Hygienist": "Healthcare",
    "Human Resources Recruiter": "Human Resources",
    "Medical Student": "Medical",
    "Public Relations Associate": "Marketing",
    "Medical Sales Representative": "Sales",
    "Casino Marketing Representative": "Marketing",
    "Wedding Coordinator": "Event Planning",
    "Menswear Buyer": "Retail",
    "Jewelry Designer": "Fashion",
    "Charity Accountant": "Finance",
    "Nurse Practitioner": "Healthcare",
    "Marketing Representative": "Marketing",
    "College Admissions": "Education",
    "Swimsuit Model": "Fashion",
    "Advertising Account Manager": "Marketing",
    "Wardrobe Consultant": "Fashion",
    "Cosmetic Sales Manager": "Sales",
    "Corporate Flight Attendant": "Aviation",
    "Hair Stylist": "Beauty",
    "Homemaker": "Lifestyle",
    "Office Manager": "Administration",
    "Restaurant Manager": "Hospitality",
    "Model/Make-Up Artist": "Beauty",
    "Entrepreneur": "Entrepreneurship",
    "Spokesmodel": "Modeling",
    "Mortgage Loan Officer": "Finance",
    "Captain, Air National Guard": "Military",
    "Fit Model": "Fashion",
    "NBA Dancer": "Athlete",
    "Commercial Pilot": "Aviation",
    "Dance Teacher": "Education",
    "Medical Technician": "Healthcare",
    "Substitute Teacher": "Education",
    "Personal Organizer": "Organization",
    "Bridal Stylist": "Fashion",
    "Political Consultant": "Politics",
    "Leasing Consultant": "Real Estate",
    "Commercial Casting Associate": "Entertainment",
    "Real Estate Dealer": "Real Estate",
    "Oil Field Account Manager": "Sales",
    "Cosmetics Consultant": "Beauty",
    "Poker Dealer": "Gaming",
    "Health Club Manager": "Fitness",
    "Community Organizer": "Community Service",
    "Salon Owner": "Beauty",
    "Yoga Instructor": "Fitness",
    "Fashion Model": "Fashion",
    "Cruise Ship Entertainer": "Entertainment",
    "Jumbotron Operator": "Entertainment",
    "Pediatric Nurse": "Healthcare",
    "Assistant District Attorney": "Law",
    "Real Estate Agent": "Real Estate",
    "Science Educator": "Education",
    "Opera Singer": "Music",
    "Medical Sales Rep": "Sales",
    "Former NBA Dancer": "Athlete",
    "Psychiatric Nurse": "Healthcare",
    "Dog Lover": "Animal Care",
    "First Grade Teacher": "Education",
    "Music Composer": "Music",
    "Marketing Manager": "Marketing",
    "Free Spirit": "Lifestyle",
    "Local News Reporter": "Media",
    "Legal Assistant": "Law",
    "Communications Director": "Marketing",
    "Grade School Teacher": "Education",
    "Police Support Specialist": "Law Enforcement",
    "Nursing Home Owner": "Healthcare",
    "Mineral Coordinator": "Geology",
    "Personal Banker": "Finance",
    "Personal Trainer": "Fitness",
    "Fertility Nurse": "Healthcare",
    "Chiropractic Assistant": "Healthcare",
    "Dance Instructor": "Education",
    "Cosmetics Developer": "Beauty",
    "Cruise Ship Singer": "Entertainment",
    "Make-Up Artist": "Beauty",
    "Guidance Counselor": "Education",
    "Dental Assistant": "Healthcare",
    "Fashion Designer": "Fashion",
    "Former NFL Cheerleader": "Athlete",
    "News Producer": "Media",


    "Bartender": "Hospitality",
    "Fourth Grade Teacher": "Education",
    "Special Education Teacher": "Education",
    "Sport Fishing Enthusiast": "Recreation",
    "Ballet Teacher": "Education",
    "Plus-Size Model": "Fashion",
    "WWE Diva-in-Training": "Athlete",
    "High School Soccer Coach": "Sports",
    "Wedding Cake Baker": "Food",
    "Cadaver Tissue Saleswoman": "Medical",
    "Real Estate Developer": "Real Estate",
    "Software Sales Representative": "Sales",
    "Kindergarten Teacher": "Education",
    "Former News Anchor": "Media",
    "Small Business Owner": "Entrepreneurship",
    "War Veteran": "Military",
    "Unemployed": "Unemployment",
    "Property Manager": "Real Estate",
    "Dentist": "Healthcare",
    "Gerontologist": "Healthcare",
    "Fashion Buyer": "Fashion",
    "Nutritional Therapist": "Healthcare",
    "Accountant": "Finance",
    "Math Teacher": "Education",
    "Cowgirl": "Agriculture",
    "Chicken Enthusiast": "Agriculture",
    "Fashion Boutique Owner": "Entrepreneurship",
    "Business Owner": "Entrepreneurship",
    "Neonatal Nurse": "Healthcare",
    "Pilates Instructor": "Fitness",
    "Pro Basketball Dancer": "Athlete",
    "Aspiring Dolphin Trainer": "Animal Care",
    "Chef": "Food",
    "Mental Health Counselor": "Therapy",
    "Plastic Surgery Office Manager": "Healthcare",
    "Travel Nurse": "Healthcare",
    "Wedding Videographer": "Photography",
    "Restaurant Server": "Hospitality",
    "Digital Marketing Manager": "Marketing",
    "Doula": "Healthcare",
    "Surgical Unit Nurse": "Healthcare",
    "Law School Graduate": "Law",
    "Food Truck Owner": "Food",
    "Apparel Sales Representative": "Sales",
    "Technology Salesperson": "Sales",
    "Creative Director": "Design",
    "Physical Therapist": "Healthcare",
    "Research Coordinator": "Research",
    "Real Estate Executive Assistant": "Real Estate",
    "Social Media Manager": "Marketing",
    "Fitness Coach": "Fitness",
    "Restaurant Owner": "Hospitality",
    "Tech Recruiter": "Human Resources",
    "Event Designer": "Event Planning",
    "Server": "Hospitality",
    "Personal Stylist": "Fashion",
    "Sports Reporter": "Media",
    "Television Host": "Media",
    "Recent Master's Graduate": "Education",
    "Orthopedic Nurse": "Healthcare",
    "Marketing Associate": "Marketing",
    "Speech Pathologist": "Healthcare",
    "Content Creator": "Media",
    "Phlebotomist": "Healthcare",
    "Miss North Carolina USA 2018": "Beauty Pageant",
    "Assistant Program Manager": "Management",
    "Miss Alabama USA 2018": "Beauty Pageant",
    "Social Media Coordinator": "Marketing",
    "IT Risk Consultant": "Information Technology",
    "Makeup Artist": "Beauty",
    "Caterer": "Food",
    "Wardrobe Stylist": "Fashion",
    "DJ": "Entertainment",
    "Sales Account Manager": "Sales",
    "Dog Rescuer": "Animal Care",
    "Marketing Salesperson": "Sales",
    "Financial Associate": "Finance",
    "Recruiter": "Human Resources",
    "Sloth": "Zoology",
    "Broadcast Journalist": "Media",
    "Cinderella": "Fictional Character",
    "Nurse": "Healthcare",
    "Business Development Associate": "Business Development",
    "Foster Parent Recruiter": "Human Services",
    "Professional Clothier": "Fashion",
    "Fashion Blogger": "Fashion",
    "Retail Marketing Manager": "Marketing",
    "House Flipper": "Real Estate",


    "Marketing Coordinator": "Marketing",
    "Home Care Coordinator": "Healthcare",
    "Orthodontist Assistant": "Dental",
    "Client Relations Manager": "Management",
    "Medical Radiographer": "Healthcare",
    "Cosmetologist": "Beauty",
    "Marketing Executive": "Marketing",
    "Business Development Rep": "Business",
    "Cattle Rancher": "Agriculture",
    "Media Buyer": "Media",
    "Nursing Student": "Student",
    "Pro NBA Dancer": "Entertainment",
    "Entertainment Sales Associate": "Sales",
    "Patient Care Coordinator": "Healthcare",
    "Communications Manager": "Management",
    "Social Media Marketer": "Marketing",
    "Fashion Entrepreneur": "Fashion",
    "Client Financial Manager": "Finance",
    "Runway Model": "Fashion",
    "Bank Marketing Manager": "Marketing",
    "Pharmacist": "Healthcare",
    "Dancer/Choreographer": "Entertainment",
    "Former Miss Universe Puerto Rico": "Entertainment",
    "Corporate Attorney": "Legal",
    "Marketing Director": "Marketing",
    "Queen": "Royalty",
    "Copywriter": "Writing",

    "Hostess": "Hospitality",
    "Healthcare Advocate": "Healthcare",
    "ICU Nurse": "Healthcare",
    "Health Food Developer": "Healthcare",
    "Event Coordinator": "Event Management",
    "Marketing Specialist": "Marketing",
    "Professional Ballerina": "Entertainment",
    "Airline Recruiter": "Aviation",
    "IT Consultant": "Information Technology",
    "Flight Instructor": "Aviation",
    "Elementary School Teacher": "Education",
    "Wealth Management Advisor": "Finance",
    "Human Resources Specialist": "Human Resources",
    "Former Olympian": "Athlete",
    "Architectural Historian": "Architecture",
    "Industrial Sales Representative": "Sales",
    "Real Estate Advisor": "Real Estate",
    "Law Student": "Legal",
    "Bar Mitzvah Dancer": "Entertainment",
    "Social Media Director": "Social Media",
    "Occupational Therapist": "Healthcare",
    "Spray Tanner": "Beauty",
    "Senior Account Executive": "Sales",
    "Child and Family Therapist": "Therapy",
    "Rodeo Racer": "Athlete",
    "Healthcare Strategist": "Healthcare",
    "E-Commerce Coordinator": "E-Commerce",
    "Postpartum Nurse": "Healthcare",
    "Nonprofit Case Manager": "Nonprofit",
    "Content Marketing Manager": "Marketing",
    "Professional Dancer": "Entertainment",
    "Hospitality Manager": "Hospitality",
    "Professional Makeup Artist": "Beauty",
    "Corporate Recruiter": "Human Resources",
    "Insurance Marketer": "Insurance",
    "Financial Advisor": "Finance",
    "Patient Care Technician": "Healthcare",
    "Stylist": "Beauty",
    "Restaurant Marketer": "Marketing",
    "Junior Project Manager": "Project Management",
    "PA Student": "Student",


    "Radiochemist": "Science",
    "Digital Strategist": "Digital Marketing",
    "Mental Health Therapist": "Therapy",
    "Vintage Store Owner": "Retail",
    "Leasing Agent": "Real Estate",
    "Finance Writer": "Finance",
    "Nursing Professor": "Education",
    "CPA": "Finance",
    "Miami Dolphins Cheerleader": "Athlete",
    "Cybersecurity Consultant": "Information Technology",
    "Artist": "Art",
}


# Define a function to map specific job titles to general categories
def map_job_title(job_title):
    for specific_job, category in job_title_to_category.items():
        if specific_job in job_title:
            return category
        
    print(f"Unmapped job title: {job_title}")
    return "Other"  # If the job title doesn't match any specific job, categorize it as "Other"

# Read the CSV file
with open('generalized-data.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    rows = list(reader)

# Update the job titles to general categories
for row in rows:
    job_title = row['job']
    category = map_job_title(job_title)
    row['job'] = category

# Write the updated data back to the CSV file
with open('updated_file.csv', 'w', newline='') as csvfile:
    fieldnames = ['season', 'name', 'age', 'hometown', 'job', 'outcome']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
